//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Github/DropletsInMotion/DropletsInMotion/language/Microfluidics.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MicrofluidicsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMicrofluidicsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MicrofluidicsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MicrofluidicsParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MicrofluidicsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MicrofluidicsParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MicrofluidicsParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MicrofluidicsParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MicrofluidicsParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MicrofluidicsParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MicrofluidicsParser.dropletDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropletDeclaration([NotNull] MicrofluidicsParser.DropletDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MicrofluidicsParser.dropletDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropletDeclaration([NotNull] MicrofluidicsParser.DropletDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MicrofluidicsParser.moveDroplet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveDroplet([NotNull] MicrofluidicsParser.MoveDropletContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MicrofluidicsParser.moveDroplet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveDroplet([NotNull] MicrofluidicsParser.MoveDropletContext context);
}
